# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_display_test_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2500, 1440)
        MainWindow.setMinimumSize(QtCore.QSize(800, 800))
        MainWindow.setMaximumSize(QtCore.QSize(2560, 1440))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(2560, 1440))
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 255, 255);  /* 深灰色背景 */\n"
"    \n"
"    \n"
"    border-radius: 10px;  /* 圆角 */\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setMinimumSize(QtCore.QSize(2000, 150))
        self.widget_5.setMaximumSize(QtCore.QSize(2500, 200))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_10 = QtWidgets.QWidget(self.widget_5)
        self.widget_10.setMinimumSize(QtCore.QSize(1200, 100))
        self.widget_10.setMaximumSize(QtCore.QSize(1500, 200))
        self.widget_10.setStyleSheet("QWidget{\n"
"    background-color: rgb(198, 198, 198);  /* 深灰色背景 */\n"
"    \n"
"    \n"
"    border-radius: 10px;  /* 圆角 */\n"
"}")
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.widget = QtWidgets.QWidget(self.widget_10)
        self.widget.setMinimumSize(QtCore.QSize(300, 50))
        self.widget.setMaximumSize(QtCore.QSize(400, 150))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(250, 50))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    qproperty-alignment:AlignCenter;\n"
"       rgb:(0, 0, 0);\n"
"    font: bold 12pt \"Times New Roman\";\n"
"    border: 3px solid white; /* 边框 */\n"
"    border-radius: 12px;\n"
"}")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_4.setStyleSheet(" QPushButton {\n"
"            background-color: blue; /* 设置背景颜色为天蓝色 */\n"
"            color: white; /* 设置文本颜色为白色 */\n"
"            border: none; /* 移除默认边框 */\n"
"            border-radius: 25px; /* 设置圆角半径 */\n"
"            font: bold 15pt \"Times New Roman\"; /* 设置字体样式 */\n"
"        }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit.setMaximumSize(QtCore.QSize(300, 50))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    qproperty-alignment:AlignCenter;\n"
"       rgb:(0, 0, 0);\n"
"    font: bold 10pt \"Times New Roman\";\n"
"    border: 3px solid white; /* 边框 */\n"
"    border-radius: 12px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    qproperty-alignment:AlignCenter;\n"
"       rgb:(0, 0, 0);\n"
"    font: bold 10pt \"Times New Roman\";\n"
"    border: 3px solid white; /* 边框 */\n"
"    border-radius: 15px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_22.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.widget_10)
        self.widget_2.setMinimumSize(QtCore.QSize(300, 50))
        self.widget_2.setMaximumSize(QtCore.QSize(400, 150))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(300, 50))
        self.lineEdit_17.setStyleSheet("QLineEdit {\n"
"    qproperty-alignment:AlignCenter;\n"
"       rgb:(0, 0, 0);\n"
"    font: bold 12pt \"Times New Roman\";\n"
"    border: 3px solid white; /* 边框 */\n"
"    border-radius: 12px;\n"
"}")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_14.addWidget(self.lineEdit_17)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_5.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_5.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_5.setStyleSheet(" QPushButton {\n"
"            background-color: blue; /* 设置背景颜色为天蓝色 */\n"
"            color: white; /* 设置文本颜色为白色 */\n"
"            border: none; /* 移除默认边框 */\n"
"            border-radius: 25px; /* 设置圆角半径 */\n"
"            font: bold 15pt \"Times New Roman\"; /* 设置字体样式 */\n"
"        }")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_14.addWidget(self.pushButton_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    qproperty-alignment:AlignCenter;\n"
"       rgb:(0, 0, 0);\n"
"    font: bold 12pt \"Times New Roman\";\n"
"    border: 3px solid white; /* 边框 */\n"
"    border-radius: 12px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_22.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_10)
        self.widget_3.setMinimumSize(QtCore.QSize(300, 50))
        self.widget_3.setMaximumSize(QtCore.QSize(400, 150))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_18.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_18.setMaximumSize(QtCore.QSize(300, 50))
        self.lineEdit_18.setStyleSheet("QLineEdit {\n"
"    qproperty-alignment:AlignCenter;\n"
"       rgb:(0, 0, 0);\n"
"    font: bold 12pt \"Times New Roman\";\n"
"    border: 3px solid white; /* 边框 */\n"
"    border-radius: 12px;\n"
"}")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_5.addWidget(self.lineEdit_18)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_6.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_6.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_6.setStyleSheet(" QPushButton {\n"
"            background-color: blue; /* 设置背景颜色为天蓝色 */\n"
"            color: white; /* 设置文本颜色为白色 */\n"
"            border: none; /* 移除默认边框 */\n"
"            border-radius: 25px; /* 设置圆角半径 */\n"
"            font: bold 15pt \"Times New Roman\"; /* 设置字体样式 */\n"
"        }")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.comboBox = QtWidgets.QComboBox(self.widget_3)
        self.comboBox.setMinimumSize(QtCore.QSize(176, 20))
        self.comboBox.setMaximumSize(QtCore.QSize(250, 50))
        self.comboBox.setStyleSheet("        QComboBox {\n"
"            color: black; /* 文本颜色 */\n"
"            font: bold 12pt \"Times New Roman\"; /* 字体样式 */\n"
"            border: 3px solid white; /* 边框 */\n"
"            border-radius: 10px; /* 圆角 */\n"
"            padding: 10px; /* 内边距 */\n"
"            min-width: 150px; /* 最小宽度 */\n"
"        }\n"
"\n"
"        QComboBox::drop-down {\n"
"            subcontrol-origin: padding;\n"
"            subcontrol-position: top right;\n"
"            width: 20px; /* 下拉按钮宽度 */\n"
"            border-left-width: 1px;\n"
"            border-left-color: darkgray;\n"
"            border-left-style: solid; /* 下拉按钮左边框 */\n"
"            border-top-right-radius: 3px; /* 下拉按钮圆角 */\n"
"            border-bottom-right-radius: 3px; /* 下拉按钮圆角 */\n"
"        }")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_15.addWidget(self.comboBox)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_7.setMinimumSize(QtCore.QSize(50, 20))
        self.pushButton_7.setMaximumSize(QtCore.QSize(250, 50))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    qproperty-alignment:AlignCenter;\n"
"       rgb:(0, 0, 0);\n"
"    font: bold 12pt \"Times New Roman\";\n"
"    border: 3px solid white; /* 边框 */\n"
"    border-radius: 12px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_15.addWidget(self.pushButton_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_22.addWidget(self.widget_3)
        self.widget_7 = QtWidgets.QWidget(self.widget_10)
        self.widget_7.setMinimumSize(QtCore.QSize(300, 50))
        self.widget_7.setMaximumSize(QtCore.QSize(400, 150))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit_19.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_19.setMaximumSize(QtCore.QSize(300, 50))
        self.lineEdit_19.setStyleSheet("QLineEdit {\n"
"    qproperty-alignment:AlignCenter;\n"
"       rgb:(0, 0, 0);\n"
"    font: bold 12pt \"Times New Roman\";\n"
"    border: 3px solid white; /* 边框 */\n"
"    border-radius: 12px;\n"
"}")
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_16.addWidget(self.lineEdit_19)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_8.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_8.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_8.setStyleSheet(" QPushButton {\n"
"            background-color: blue; /* 设置背景颜色为天蓝色 */\n"
"            color: white; /* 设置文本颜色为白色 */\n"
"            border: none; /* 移除默认边框 */\n"
"            border-radius: 25px; /* 设置圆角半径 */\n"
"            font: bold 15pt \"Times New Roman\"; /* 设置字体样式 */\n"
"        }")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_16.addWidget(self.pushButton_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_3.setMinimumSize(QtCore.QSize(176, 20))
        self.comboBox_3.setMaximumSize(QtCore.QSize(250, 50))
        self.comboBox_3.setStyleSheet("        QComboBox {\n"
"            color: black; /* 文本颜色 */\n"
"            font: bold 12pt \"Times New Roman\"; /* 字体样式 */\n"
"            border: 3px solid white; /* 边框 */\n"
"            border-radius: 10px; /* 圆角 */\n"
"            padding: 10px; /* 内边距 */\n"
"            min-width: 150px; /* 最小宽度 */\n"
"        }\n"
"\n"
"        QComboBox::drop-down {\n"
"            subcontrol-origin: padding;\n"
"            subcontrol-position: top right;\n"
"            width: 20px; /* 下拉按钮宽度 */\n"
"            border-left-width: 1px;\n"
"            border-left-color: darkgray;\n"
"            border-left-style: solid; /* 下拉按钮左边框 */\n"
"            border-top-right-radius: 3px; /* 下拉按钮圆角 */\n"
"            border-bottom-right-radius: 3px; /* 下拉按钮圆角 */\n"
"        }")
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_17.addWidget(self.comboBox_3)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_9.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButton_9.setMaximumSize(QtCore.QSize(250, 50))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    qproperty-alignment:AlignCenter;\n"
"       rgb:(0, 0, 0);\n"
"    font: bold 12pt \"Times New Roman\";\n"
"    border: 3px solid white; /* 边框 */\n"
"    border-radius: 12px;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_17.addWidget(self.pushButton_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_22.addWidget(self.widget_7)
        self.horizontalLayout_7.addWidget(self.widget_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        self.widget_8.setMinimumSize(QtCore.QSize(300, 100))
        self.widget_8.setMaximumSize(QtCore.QSize(400, 200))
        self.widget_8.setStyleSheet("QWidget{\n"
"    background-color: rgb(153, 255, 204);  /* 深灰色背景 */\n"
"    \n"
"    \n"
"    border-radius: 10px;  /* 圆角 */\n"
"}")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit_20.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_20.setMaximumSize(QtCore.QSize(300, 50))
        self.lineEdit_20.setStyleSheet("QLineEdit {\n"
"    qproperty-alignment:AlignCenter;\n"
"       rgb:(0, 0, 0);\n"
"    font: bold 12pt \"Times New Roman\";\n"
"    border: 3px solid white; /* 边框 */\n"
"    border-radius: 12px;\n"
"}")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_18.addWidget(self.lineEdit_20)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_10.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_10.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_10.setStyleSheet(" QPushButton {\n"
"            background-color: blue; /* 设置背景颜色为天蓝色 */\n"
"            color: white; /* 设置文本颜色为白色 */\n"
"            border: none; /* 移除默认边框 */\n"
"            border-radius: 25px; /* 设置圆角半径 */\n"
"            font: bold 15pt \"Times New Roman\"; /* 设置字体样式 */\n"
"        }")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_18.addWidget(self.pushButton_10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_2.setMinimumSize(QtCore.QSize(166, 20))
        self.comboBox_2.setMaximumSize(QtCore.QSize(250, 50))
        self.comboBox_2.setStyleSheet("        QComboBox {\n"
"            color: black; /* 文本颜色 */\n"
"            font: bold 12pt \"Times New Roman\"; /* 字体样式 */\n"
"            border: 3px solid white; /* 边框 */\n"
"            border-radius: 10px; /* 圆角 */\n"
"            padding: 5px; /* 内边距 */\n"
"            min-width: 150px; /* 最小宽度 */\n"
"        }\n"
"\n"
"        QComboBox::drop-down {\n"
"            subcontrol-origin: padding;\n"
"            subcontrol-position: top right;\n"
"            width: 20px; /* 下拉按钮宽度 */\n"
"            border-left-width: 1px;\n"
"            border-left-color: darkgray;\n"
"            border-left-style: solid; /* 下拉按钮左边框 */\n"
"            border-top-right-radius: 3px; /* 下拉按钮圆角 */\n"
"            border-bottom-right-radius: 3px; /* 下拉按钮圆角 */\n"
"        }")
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_19.addWidget(self.comboBox_2)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_11.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_11.setMaximumSize(QtCore.QSize(250, 50))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    qproperty-alignment:AlignCenter;\n"
"       rgb:(0, 0, 0);\n"
"    font: bold 12pt \"Times New Roman\";\n"
"    border: 3px solid white; /* 边框 */\n"
"    border-radius: 12px;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_19.addWidget(self.pushButton_11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_7.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.widget_5)
        self.widget_9.setMinimumSize(QtCore.QSize(300, 100))
        self.widget_9.setMaximumSize(QtCore.QSize(400, 200))
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit_21.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_21.setMaximumSize(QtCore.QSize(300, 50))
        self.lineEdit_21.setStyleSheet("QLineEdit {\n"
"    qproperty-alignment:AlignCenter;\n"
"       rgb:(0, 0, 0);\n"
"    font: bold 12pt \"Times New Roman\";\n"
"    border: 3px solid gray; /* 边框 */\n"
"    border-radius: 12px;\n"
"}")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_20.addWidget(self.lineEdit_21)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_12.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_12.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_12.setStyleSheet(" QPushButton {\n"
"            background-color: blue; /* 设置背景颜色为天蓝色 */\n"
"            color: white; /* 设置文本颜色为白色 */\n"
"            border: none; /* 移除默认边框 */\n"
"            border-radius: 25px; /* 设置圆角半径 */\n"
"            font: bold 15pt \"Times New Roman\"; /* 设置字体样式 */\n"
"        }")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_20.addWidget(self.pushButton_12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 20))
        self.pushButton_2.setMaximumSize(QtCore.QSize(400, 50))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    qproperty-alignment:AlignCenter;\n"
"       rgb:(0, 0, 0);\n"
"    font: bold 12pt \"Times New Roman\";\n"
"    border: 3px solid gray; /* 边框 */\n"
"    border-radius: 12px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_21.addWidget(self.pushButton_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_7.addWidget(self.widget_9)
        self.verticalLayout_10.addWidget(self.widget_5)
        self.widget_13 = QtWidgets.QWidget(self.centralwidget)
        self.widget_13.setMinimumSize(QtCore.QSize(600, 400))
        self.widget_13.setMaximumSize(QtCore.QSize(2500, 1000))
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_24.addLayout(self.gridLayout)
        self.widget_11 = QtWidgets.QWidget(self.widget_13)
        self.widget_11.setMinimumSize(QtCore.QSize(800, 800))
        self.widget_11.setMaximumSize(QtCore.QSize(1000, 1000))
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label = QtWidgets.QLabel(self.widget_11)
        self.label.setMinimumSize(QtCore.QSize(800, 800))
        self.label.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_23.addWidget(self.label)
        self.horizontalLayout_24.addWidget(self.widget_11)
        self.verticalLayout_10.addWidget(self.widget_13)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setMinimumSize(QtCore.QSize(600, 100))
        self.widget_4.setMaximumSize(QtCore.QSize(2500, 200))
        self.widget_4.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 255, 255);  /* 白色背景 */\n"
"    \n"
"    \n"
"    border-radius: 10px;  /* 圆角 */\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setMinimumSize(QtCore.QSize(150, 150))
        self.label_3.setMaximumSize(QtCore.QSize(200, 200))
        self.label_3.setStyleSheet("image: url(:/all/img_show/icon1.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setMinimumSize(QtCore.QSize(150, 150))
        self.label_2.setMaximumSize(QtCore.QSize(200, 200))
        self.label_2.setStyleSheet("image: url(:/all/img_show/icon2.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_10.addWidget(self.widget_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_2.setText(_translate("MainWindow", "1. Load point cloud"))
        self.pushButton_4.setText(_translate("MainWindow", "!"))
        self.lineEdit.setText(_translate("MainWindow", "Input file path"))
        self.pushButton.setText(_translate("MainWindow", "..."))
        self.lineEdit_17.setText(_translate("MainWindow", "2. Preprocessing"))
        self.pushButton_5.setText(_translate("MainWindow", "!"))
        self.pushButton_3.setText(_translate("MainWindow", "Start processing"))
        self.lineEdit_18.setText(_translate("MainWindow", "3. Plane detection"))
        self.pushButton_6.setText(_translate("MainWindow", "!"))
        self.pushButton_7.setText(_translate("MainWindow", "Detect"))
        self.lineEdit_19.setText(_translate("MainWindow", "4. Hole extraction"))
        self.pushButton_8.setText(_translate("MainWindow", "!"))
        self.pushButton_9.setText(_translate("MainWindow", "Extract"))
        self.lineEdit_20.setText(_translate("MainWindow", "5.Parameter extraction"))
        self.pushButton_10.setText(_translate("MainWindow", "!"))
        self.pushButton_11.setText(_translate("MainWindow", "Generate"))
        self.lineEdit_21.setText(_translate("MainWindow", "6. Save point cloud"))
        self.pushButton_12.setText(_translate("MainWindow", "!"))
        self.pushButton_2.setText(_translate("MainWindow", "Save as"))
import img_test_rc
